### ISSUE TITLE
Module 2 section Update Mythical Mysfits to Call the NLB

### ISSUE THREAD

**Issue by wksantiago** [aws-samples/aws-modern-application-workshop#105]
In Module section Update Mythical Mysfits to Call the NLB
Right after Upload to S3
When testing website using the same URL used at the end of Module 1
The page starts OK but the individual MysFits do  not sho up just the header and footer.

Maybe this is normal and will be corrected after Module 3

**Comment by abaird986** [comment]
This can happen due to browser caching behavior of the ECS tasks aren't yet available behind the NLB when you've deployed the service.  Try using curl in the Cloud9 IDE command line to confirm the service *is* up and running.  

`curl <inser_nlb_url>/mysfits`

If curl returns the appropriate , and the page still won't show the mysfits, do a browser hard refresh and/or browser cache clear. That should fix the issue.

**Comment by wksantiago** [comment]
Andrew I tried  the curl command and the application is working OK but the link: https://d32ds3e8qx3atn.cloudfront.net/
in my case gives the missing Mysfits same result.

I tried it in a different PC
Thanks,

**Comment by wksantiago** [comment]
the nlb_url works great: http://mysfits-nlb-b389838c0a6612f1.elb.us-east-1.amazonaws.com/mysfits

**Comment by wksantiago** [comment]
I got to Module 4 and when I refreshed the URL: https://d32ds3e8qx3atn.cloudfront.net/
It worked.  So module 4 is OK

**Comment by abaird986** [comment]
If the NLB URL worked, and after module 4 things were working ok, I suspect it was either a browser cache thing... or if there was lots of time between attempts and it wasn't a browser cache thing, I suspect there may have been an issue in the index.html file modified and uploaded after module 2 (it can fail unless the NLB endpoint is inserted just as the comment next to it shows in index.html).

Either way, I'm glad you're past the issue and things are working now.  If you run into another error/problem, don't hesitate to open up another issue!
