### ISSUE TITLE
Cloudformation Access Denied

### ISSUE THREAD

**Issue by VeronaMark** [aws-samples/aws-modern-application-workshop#42]
I'm at the first step of the second module...and I've been here sometime.  I presume my IAM user doesn't have a correct policy assigned? How can I proceed?  Thank you.

Marksdaily:~/environment $ aws cloudformation create-stack --stack-name MythicalMysfitsCoreStack --capabilities CAPABILITY_NAMED_IAM --template-body file://~/environment/aws-modern-application-workshop/module-2/cfn/core.yml

An error occurred (AccessDenied) when calling the CreateStack operation: User: arn:aws:iam::780963802580:user/Marksdaily is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:us-west-2:780963802580:stack/MythicalMysfitsCoreStack/*
Marksdaily:~/environment $

**Comment by abaird986** [comment]
Hi @VeronaMark ! 

Sorry about the error you're receiving. You're right that this error indicates the IAM Policy assigned to your IAM User account does not have sufficient permissions.  Because this tutorial requires the use of many different AWS services, along with the ability to create new IAM Roles/Policies, we recommend you assign the "Administrator" policy to your IAM User/Group in order to complete the workshop.

Thanks for taking part in the tutorial!

**Comment by VeronaMark** [comment]
Thank you, with your suggestion I am now proceeding happily:  "StackStatus": "CREATE_IN_PROGRESS"

Things aren't quite right though if you invite us (rightly) to not use the root user.. but then we need to use anyway the AdministratorAccess on the IAM defined user that we're invited to define
