### ISSUE TITLE
Missing Directories

### ISSUE THREAD

**Issue by Daeltaja** [aws-samples/aws-modern-application-workshop#45]
As per the guide https://aws.amazon.com/getting-started/projects/build-modern-app-fargate-lambda-dynamodb-python/module-one/ I can't progress passed the bucket policy step, as it appears the module directories are missing. 

For example, the following directories are missing:
/module-1/aws-cli/website-bucket-policy.json 
/module-1/web/index.html

Any chance these could be added back to the git repo so I can continue the workshop?

Thank you.

**Comment by abaird986** [comment]
Hi @Daeltaja, sorry for the issues you're encountering.  The Developer Center version of this workshop (the one you linked to) has unfortunately fallen out of date with this GitHub repository.  The workshop in GitHub has evolved faster than our Marketing site version of the workshop could keep up.

To continue the workshop, please follow the instructions located on the README of the GitHub repository, rather than the instructions on the site you linked to.  Find the first module for the Python workshop linked to from here: https://github.com/aws-samples/aws-modern-application-workshop/tree/python (follow the link within this README to Proceed to Module 1).

Apologies for the confusion again!
