### ISSUE TITLE
[fargate] workshop-3 Lab 4: Create stack error

### ISSUE THREAD

**Issue by 178inaba** [aws-samples/aws-modern-application-workshop#66]
https://github.com/aws-samples/aws-modern-application-workshop/tree/fargate/workshop-3#42-generate-load-to-test-the-scaling-policy
Stack creation for this section will fail.

```
The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (Service: AmazonEC2; Status Code: 400; Error Code: VPCResourceNotSpecified;
```

I have identified the problem.
https://s3.amazonaws.com/mythical-mysfits-website/fargate-ops/load-gen-lab4.yml
The InstanceType in this yaml is wrong.

The error has been resolved by changing it as follows.

```diff
-      InstanceType: m4.large
+      InstanceType: m3.large
```

**Comment by abaird986** [comment]
Any chance your AWS account is more than a few years old? This type of error would exist if your account still has access to "EC2 Classic" where instances do not need to run inside of VPC.  It's not an error that a new account would encounter, and unfortunately some of the instructions in the lab would only required to be changed for older accounts like I suspect yours may be.

The change you can take, is to ensure that any commands where vpc-id or subnet-id is an option parameter, is a required parameter in your account. Otherwise, the command may try to create resources outside of VPC inside EC2 Classic where instance types more recent than the m3 family may not be supported, etc.

Hope that clarifies what you ran into, sorry for the unique situation though!
